# Generated by Django 4.1.3 on 2022-11-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='아이템 제목')),
                ('category', models.IntegerField(verbose_name='카테고리')),
                ('seller', models.IntegerField(verbose_name='판매자 번호')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('discountedPrice', models.IntegerField(default=0, verbose_name='할인가')),
                ('hashtags', models.CharField(max_length=50, verbose_name='해쉬태그')),
                ('thumb', models.ImageField(blank=True, upload_to='items/thumb')),
                ('detail', models.ImageField(blank=True, upload_to='items/detail')),
            ],
        ),
    ]
