# Generated by Django 4.1.3 on 2022-11-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='itemnumber',
        ),
    ]
