# Generated by Django 4.1.3 on 2022-11-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_rename_id_item_itemnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemnumber',
            new_name='id',
        ),
    ]
