# Generated by Django 4.1.3 on 2022-11-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_itemnumber_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='item_id',
        ),
    ]
