# Generated by Django 4.1.3 on 2022-11-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_rename_id_item_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.CharField(max_length=255, verbose_name='판매자 닉네임'),
        ),
    ]
