# Generated by Django 4.1.3 on 2022-11-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='detail',
            field=models.TextField(verbose_name='상세'),
        ),
        migrations.AlterField(
            model_name='item',
            name='thumb',
            field=models.TextField(verbose_name='썸네일'),
        ),
    ]
