# Generated by Django 4.1.3 on 2022-11-03 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('linked_item', models.IntegerField(verbose_name='연결된 아이템')),
                ('linked_user', models.CharField(max_length=255, verbose_name='작성자 닉네임')),
                ('score', models.IntegerField(verbose_name='점수')),
                ('text', models.TextField(verbose_name='본문')),
                ('written_date', models.DateField(default=datetime.date.today, verbose_name='작성 일자')),
            ],
        ),
    ]
