# Generated by Django 4.1.3 on 2022-11-03 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='주문 일자')),
                ('experience_date', models.DateField(verbose_name='체험 일자')),
                ('linked_item', models.IntegerField(verbose_name='연결된 아이템')),
                ('linked_user', models.CharField(max_length=255, verbose_name='주문자 닉네임')),
                ('orderer_name', models.CharField(max_length=255, verbose_name='주문에 쓰인 이름')),
                ('orderer_phone', models.CharField(max_length=255, verbose_name='주문에 쓰인 전화번호')),
                ('orderer_email', models.CharField(max_length=255, verbose_name='주문에 쓰인 이메일')),
            ],
        ),
    ]
