# Generated by Django 4.1.3 on 2022-11-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자')),
                ('email', models.CharField(default='', max_length=255, unique=True, verbose_name='이메일')),
                ('point', models.IntegerField(default=0, verbose_name='포인트')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
