# Generated by Django 4.1.3 on 2022-11-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='usernumber',
        ),
    ]
