# Generated by Django 4.1.3 on 2022-11-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_id_user_usernumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usernumber',
            new_name='id',
        ),
    ]
