# Generated by Django 4.1.3 on 2022-11-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_usernumber_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
